### PR TITLE
Files to install on Arch Linux

### PR DESCRIPTION
**Pull request by frap129**
Hey, I've been using KTweak on my arch linux laptop for a couple weeks now and I thought the package install files might be useful to someone else. I don't plan on maintaining this as an AUR package, but given that nothing about ktweak changes drastically then this setup should work forever.

### CODE REVIEW

**Comment by tytydraco** [comment]
Ah that's awesome! I had it setup in my systemd manually but this is much nicer. Thanks for the PR :)

**Comment by frap129** [comment]
Fastest PR merge I've seen lol. Glad I could help!

**Comment by garysams220** [comment]
#

**Review by wilsontory00 — APPROVED** [review]

**Comment by garysams220** [comment]
@

**Comment by garysams220** [comment]
@[]()

**Review by juancarloschavezruiz31-create — CHANGES_REQUESTED** [review]
c7faf14f2acc0b8663cec85a514077a174392910

**Comment by juancarloschavezruiz31-create** [comment]
Dalvik/2.1.0 (Linux; U; Android 13; SM-A037M Build/TP1A.220624.014)

**Comment by juancarloschavezruiz31-create** [comment]
juancarloschavezruiz31-crea
Código de verificación: 400372
Dispositivo: Samsung Browser en Android
Gracias,equipo de GitHub

**Comment by juancarloschavezruiz31-create** [comment]
Dalvik/2.1.0 (Linux; U; Android 13; SM-A037M Build/TP1A.220624.014)

**Pull request merged**
