### PR TITLE
Update ktweak

### PR DESCRIPTION
**Pull request by Baonks81**

### CODE REVIEW

**Comment by Baonks81** [comment]
Increase sched_task to 16, decrease shed_nr_migrate to 2

**Comment by tytydraco** [comment]
I'm concerned that we may be pushing the limits here. At a certain point, we will be switching tasks so often that we lose a significant chunk of processing speed. Perhaps we should run some benchmarks, schbench and backbench.

**Comment by Baonks81** [comment]
I just tested ktweak latency branch on my tablet run android and linux mobile kernel(postmarketOS), it run smooth with maximum cpu frequency, the temperature was around 48-50 celsius degrees. Let's run benchmark, schbench and backbench

**Review by justinmjohnson37 — APPROVED** [review]

**Comment by NitroVenom** [comment]
Kys

**Pull request closed without merging**
